### ISSUE TITLE
ValueError: Could not load ""  Reason: "image file is truncated"

### ISSUE THREAD

**Issue by lh641446825** [kirumang/Pix2Pose#2]
Hello, I am in trouble when I run the `5_evaluation_bop_basic.py` file. The error is: 

```
Recognizing scene_id:9, im_id:242
Recognizing scene_id:9, im_id:243
Traceback (most recent call last):
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/PIL/ImageFile.py", line 235, in load
    s = read(self.decodermaxblock)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 659, in load_read
    cid, pos, length = self.png.read()
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 122, in read
    length = i32(s)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/PIL/_binary.py", line 82, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 671, in pil_try_read
    im.getdata()[0]
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/PIL/Image.py", line 1304, in getdata
    self.load()
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/PIL/ImageFile.py", line 241, in load
    raise IOError("image file is truncated")
OSError: image file is truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Pix2Pose/tools/5_evaluation_bop_basic.py", line 261, in <module>
    image_t = inout.load_im(rgb_path)            
  File "./bop_toolkit/bop_toolkit_lib/inout.py", line 22, in load_im
    im = imageio.imread(path)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/core/format.py", line 164, in get_reader
    return self.Reader(self, request)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/core/format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 300, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 137, in _open
    pil_try_read(self._im)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 682, in pil_try_read
    raise ValueError(error_message)
ValueError: Could not load "" 
Reason: "image file is truncated"
Please see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries

```

I downloaded the T-LESS dataset from the [BOP](https://bop.felk.cvut.cz/datasets/), which lacks images 08-109.png, 08-110.png, 09-244.png, 14-367.png, 18-497.png. I downloaded the corresponding file from the [official website](http://cmp.felk.cvut.cz/t-less/download.html), and it is still error in the position of 09-244.png after being placed.

Can you tell me how to solve it?

**Comment by kirumang** [comment]
Hello, I am not so sure what is wrong with original images from the official website. 
It seems that the newly added images have problems. Could you check the images can be properly read by a normal image viewer? 
or, the BOP website also provides the full test images of T-Less in the same format. so, you can download and use them.

**Comment by lh641446825** [comment]
I downloaded the dataset from bop, but it lacks images, and the program will report an error, so I downloaded the missing image from the official website and still reported an error.

**Comment by kirumang** [comment]
It's weird. I downloaded full test images from the BOP website with the link below. (a minute ago) 
[All test images] (http://ptak.felk.cvut.cz/6DB/public/bop_datasets/tless_test_primesense_all.zip
)
And, there are 09-000244.png and others. If you still need those files, please send me an email, I will send you images. 

or, you could try to load images with other image libraries.
(e.g., replace line 261 in 5_evaluation_bop_basic.py with "image_t = cv2.imread(rgb_path)[:,:,::-1]         ")

**Comment by lh641446825** [comment]
Thank you. It may be a problem with our campus network. It was interrupted several times in the middle of the download process. I remember that it was interrupted in the middle when I downloaded the last time. I tried to use the method provided on the BOP.
```
export SRC=http://ptak.felk.cvut.cz/6DB/public/bop_datasets
wget $SRC/tless_test_primesense_all.zip 
```
The information as follow: 
> --2019-11-18 19:29:51-- (try:20) http://ptak.felk.cvut.cz/6DB/public/bop_datasets/tless_test_primesense_all.zip
> Connecting to ptak.felk.cvut.cz (ptak.felk.cvut.cz)|147.32.84.14|:80... connected.
> HTTP request sent, awaiting response... No data received.

Can you send the following three pictures(09-000244.png, 14-000367.png, 18-000497.png) to my email address? Thanks again. I am sorry to bother you for so long.
My email is 1870613@stu.neu.edu.cn.

**Comment by lh641446825** [comment]
Thank you very much for your help. Although I still haven't solved the problem after using the pictures you provided. When I try to load images with other image libraries, the error is:
```
Recognizing scene_id:9, im_id:242
Recognizing scene_id:9, im_id:243
libpng error: Read Error
Traceback (most recent call last):
  File "/home/Pix2Pose/tools/5_evaluation_bop_basic.py", line 261, in <module>
    image_t = cv2.imread(rgb_path)[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable
```
I am very sorry to trouble you for so long. I will find the reason myself. Best wish.

**Comment by lh641446825** [comment]
Hello, I solved this problem, add the following code：
```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
