### ISSUE TITLE
Error while reproducing BOP results on YCB-V using resnet50

### ISSUE THREAD

**Issue by mehtakhil** [kirumang/Pix2Pose#7]
Hello, 

Thank you for your wonderful work! I am trying to reproduce the results of BOP challenge on YCB-V dataset using both versions submitted in the BOP challenge. I am able to reproduce the results by using 'paper' as backbone but while using 'resnet50' as backbone, I get the following error.

```
load pix2pose weight for obj_1 from /home/akm7rng/Desktop/Dataset/BOP/Dataset/ycbv/pix2pose_weights/01/inference_resnet_model.hdf5
XXX lineno: 188, opcode: 0
Traceback (most recent call last):
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/network.py", line 1027, in from_config
    process_node(layer, node_data)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/network.py", line 986, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/core.py", line 682, in call
    return self.function(inputs, **arguments)
  File "/home/kiru/common_ws/Pix2Pose/pix2pose_model/ae_model.py", line 188, in <lambda>
SystemError: unknown opcode'
```
 
I am running the code with Python 3.6.3 and Keras 2.2.1.
Please let me know if you need any information from my side.
Thank you for your assistance!

**Comment by kirumang** [comment]
Hello, 
It seems the error is relevant to the versions of libraries. 
Which version of Tensorflow are you using? The code may not work if the version is higher than 2.0. 
I have tested the code with Tensorflow 1.8 and Keras 2.2.0
Let me know if it produces the same error again after changing the versions.

Anyway, thank you for trying my code and report a bug.

**Comment by mehtakhil** [comment]
Thank you for the quick reply. I changed the versions and I still get an error while trying to load the weights. 
```
recongnition.py
24.  elif(backbone=='resnet50'):
25.       self.generator_train = load_model(weight_fn)        
```
After changing the versions, I ran the evaluation with 'paper' as backbone and that works fine. I am encountering problem only with the resnet50 backbone. Here is the snipped of the error:
```
Re-starting from epoch 5
load pix2pose weight for obj_1 from /home/akm7rng/Desktop/Dataset/BOP/Dataset/ycbv/pix2pose_weights/01/inference_resnet_model.hdf5
Traceback (most recent call last):
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/network.py", line 1036, in from_config
    process_layer(layer_data)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in process_layer
    custom_objects=custom_objects)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1124, in from_config
    return cls(**config)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/convolutional.py", line 743, in __init__
    **kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/convolutional.py", line 483, in __init__
    **kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/layers/convolutional.py", line 104, in __init__
    super(_Conv, self).__init__(**kwargs)
  File "/home/akm7rng/envs/pix2pose/lib/python3.6/site-packages/keras/engine/base_layer.py", line 128, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'output_padding')

```

**Comment by kirumang** [comment]
Let me try another way then... 
Could you please download the file at the link below
[weight_file_for_ycbv_01](https://drive.google.com/open?id=1pUtksbKwnrkFwi13X0Dqo9WGz18Y8BpI)

and, replace line 25 in recongnition.py with below?
```
weight_fn ="path/to/new/weight/file"
self.generator_train = ae.aemodel_unet_resnet50(p=1.0)
self.generator_train.load_weights(weight_fn)
```
The file I linked is the weight file for the object-01 in YCB-V instead of the Keras model file.
Please let me know whether it works or not. 
If it works,  I will update the code and upload entire weight files soon.

Thanks!

**Comment by mehtakhil** [comment]
It works :). I don't get an error as of now and the model is loading fine. Once you upload the weights, I will evaluate and confirm if I am able to reproduce the results from BOP challenge.

Thank you!

**Comment by kirumang** [comment]
I updated the code and uploaded the weight files again.
Check out the line at README.md and the commit a884d7ba8f52d68a5cb6b2b564750cd0368329c3

Please let me know if this makes other problems :-).

**Comment by mehtakhil** [comment]
Hello,

I was able to reproduce the results using resnet50 for BOP challenge. You should also change the link for weights at the bottom of the page so there is no confusion for others.
https://github.com/kirumang/Pix2Pose#download-trained-weights-for-the-bop-challenge-2019

Thanks once again!

**Comment by kirumang** [comment]
Sounds great!
Thank you for pointing out. I changed the link also.
